!obj:pylearn2.train.Train {
    dataset: &train !obj:dataset_wrapper.load_data {
        path: 'adult/train_v_R.csv',
        start: 0,
        stop: 29301,
        mode: 'classification',
    },
    
    model: !obj:pylearn2.models.softmax_regression.SoftmaxRegression {
        n_classes: 2,
        irange: 0.,
        nvis: 123,
    },

    algorithm: !obj:pylearn2.training_algorithms.bgd.BGD {
        batch_size: 100,
        line_search_mode: 'exhaustive',
        conjugate: 1,
        monitoring_dataset:
            {
                'train' : *train,
                'valid' : !obj:dataset_wrapper.load_data {
                              path: 'adult/valid_v_R.csv',
                              start: 0,
                              stop: 3260,
                              mode: 'classification',
                },
                'test'  : !obj:dataset_wrapper.load_data {
                              path: 'adult/test_R.csv',
                              start: 0,
                              stop: 16281,
                              mode: 'classification',
                }
            },
        termination_criterion: !obj:pylearn2.termination_criteria.MonitorBased {
            channel_name: "valid_y_misclass"
        }
    },
    
    extensions: [
        !obj:pylearn2.train_extensions.best_params.MonitorBasedSaveBest {
             channel_name: 'valid_y_misclass',
             save_path: "softmax_regression_best.pkl"
        },
    ],
    save_path: "softmax_regression.pkl",
    save_freq: 1
    
}
